# Created by Jekyll Writer
title: My Blog
email: chq970220@gmail.com
description: welcome to my blog
permalink: '/:year/:month/:day/:title/'
twitter_username: ChanChalie
github_username: SullenChoirboy
markdown: kramdown
