# Created by Jekyll Writer
title: Sullen_Choirboy's Blog
email: chq970220@gmail.com
description: welcome to my blog
baseurl: ''
url: ''
permalink: '/:year/:month/:day/:title/'
twitter_username: ChanChalie
github_username: SullenChoirboy
facebook_username: 陈皓琪
markdown: kramdown
