# Created by Jekyll Writer
title: Sullen_Choirboy's Blog
author: SullenChoirboy
description: welcome to my blog
baseurl: ''
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: ChanCharlie
github_username: SullenChoirboy
gems: jekyll-paginate
markdown: kramdown
url: ''
